### ISSUE TITLE
[Feature]: Regional chapters button on the Slack bot

### ISSUE THREAD

**Issue by seleneyang** [chaoss/chaoss-slack-bot#100]
### Contact Details

seleneyang1@gmail.com

### The Problem

It'd be great to also showcase and let newcomers know about the regional chapters that are in place. CHAOSS Africa, CHAOSS LAC, and CHAOSS Balkans. 

### How to Fix It

We could link the button to this website: https://chaoss.community/kb/local-chapters/
As well as the links to the Slack active channels # chaoss-lac # chaoss-africa

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oliverTwist2** [comment]
I would love to take this issue

**Comment by Ruth-ikegah** [comment]
> I would love to take this issue

Assigned to you! If you have any questions while solving this issue, ask @misspee007 !

**Comment by misspee007** [comment]
Hi @oliverTwist2, do you have any update on this?

**Comment by misspee007** [comment]
Hey👋🏽 @oliverTwist2
Please let me know if you have a blocker, or if you need this to be reassigned to someone else.
