### ISSUE TITLE
[Docs]: A skipped step in Setup.md on installing a slack app

### ISSUE THREAD

**Issue by oliverTwist2** [chaoss/chaoss-slack-bot#101]
### Contact Details

oliverikegah@gmail.com

### The Problem

The docs skipped a step in installing a slack app, after you click the Create App button, a window pops up to choose what type of app you are installing, i.e. From scratch or From an app manifest. This step and the the right option to choose are not shown on the Setup.md doc.
![api issue](https://github.com/chaoss/chaoss-slack-bot/assets/104382427/384a1f87-51dc-45f1-bb25-dedc8ace0b12)

### How to Fix It

Add this step and the correct option to choose to the setup.md docs

### Specific File Path(s) on the Repo to be Modified/Refered to

https://github.com/chaoss/chaoss-slack-bot/blob/main/SETUP.md

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ise8933** [comment]
Hello! Can I be added to this?

**Comment by ise8933** [comment]
i am starting to work on this now

**Comment by misspee007** [comment]
Closing this because it has been addressed.

**Comment by misspee007** [comment]
> i am starting to work on this now

Hey, I'm so sorry I didn't get notifications for your comments. I think it's because I wasn't tagged. I just noticed that this has been addressed, but I'll assign you the next one I find. Sorry for the inconvenience 🙏🏾

**Comment by ise8933** [comment]
Hello! I dont think it has actually been addressed. I looked at the set up doc and am not seeing the extra step.  I could be wrong though!

**Comment by misspee007** [comment]
Oh! I was referencing a completely different issue. 🥲 Thank you so much for catching that. Please carry on with your work. @ise8933
