### ISSUE TITLE
Send Site-wide DM for CHAOSS Community Survey

### ISSUE THREAD

**Issue by Ruth-ikegah** [chaoss/chaoss-slack-bot#19]
**Problem**: Our Slack Bot has the feature to send site-wide DMs to all the members of the CHAOSS slack channel. We would love to activate this feature for sending our community survey. 

**How to fix it**:  Check the app.js file and go to line 114; there is a DM set up that can be edited to send the message.
You only need to edit the Text, nothing else.

**Message to add in the line of code**: Hello there! We recently launched a community survey to get your feedback on how to make our community more welcoming and inclusive. If you have considered yourself part of the community, we would love you to share your thoughts and experiences by [completing this survey](https://chaossproject.limesurvey.net/835156?lang=en).
Thank you!

**Specific file path on the repo**: https://github.com/chaoss/chaoss-slack-bot/blob/main/app.js

If you need help or have questions, ask @Preshh0 or @mide358. 

Thank you for contributing!

**Comment by adeyinkaoresanya** [comment]
I will love to take this up
