### ISSUE TITLE
CHAOSS Africa Keyword-triggered DM

### ISSUE THREAD

**Issue by misspee007** [chaoss/chaoss-slack-bot#24]
**Problem**: Our Slack Bot has the feature to respond when a member types the keyword "newbie" in the newcomers channel, by sending a DM to the person. We would love to implement a similar feature in the [#chaoss-africa](https://chaoss-workspace.slack.com/archives/C03KC6ZERSR) channel, with the keyword "africa".

**How to fix it**: 
- Create a new component the components folder and give it a descriptive name, e.g. africa.js. A similar feature is the [newbie.js.](https://github.com/chaoss/chaoss-slack-bot/blob/main/components/newbie.js). 
- Import your component in the app.js file and add an event handler. Ensure to add a descriptive comment. For example:
```
//This responds to a member when they  type newbie in any channel where the bot is present
app.message(/newbie/i, async ({ message, client, logger }) => {
	newbie.newHere(message, client, logger);
});
```
If you're not clear on how the elements (i.e text, bullet points, etc) are structured, check out this drag-and-drop tool: [block-kit builder](https://api.slack.com/block-kit)

**Message to be sent**:
......
Welcome to all our Newcomers! The goal of CHAOSS Africa is to identify and solve challenges African Open Source Contributors face and also contribute to the larger CHAOSS group. We usually have our community meetings, once every two weeks, Thursdays at 3 PM WAT!

In the meantime, you should check out our different focus group channels and join one of them depending on your skillset:
- [#chaossafrica-cm](https://chaoss-workspace.slack.com/archives/C03LUCA2988) for community managers
- [#chaossafrica-designers](https://chaoss-workspace.slack.com/archives/C03L1N9H92R) for designers
- [#chaossafrica-devs](https://chaoss-workspace.slack.com/archives/C03KQ1UQ20P) for developers
- [#chaossafrica-techwriters](https://chaoss-workspace.slack.com/archives/C03L4JCEN83) for technical writers
- [#chaossafrica-researchers](https://chaoss-workspace.slack.com/archives/C03KY46NL7Q) for researchers and data scientists

If you have any questions, you can ask [@Ruth Ikegah (She/her)](https://chaoss-workspace.slack.com/team/U0174P1MDAP) or on the channel.
.......

**Specific file path on the repo**: 
https://github.com/chaoss/chaoss-slack-bot/blob/main/components
https://github.com/chaoss/chaoss-slack-bot/blob/main/app.js

**Technical Resources**:
[Getting started with Bolt for JavaScript](https://slack.dev/bolt-js/tutorial/getting-started)
[Slack API developer docs and guides](https://api.slack.com/docs)
[Block Kit: A Clean and Consistent UI Framework for Slack Apps (allows you to drag and drop elements and copy the payload)](https://api.slack.com/block-kit)

If you need help or have questions, ask @Preshh0, @mide358 or @misspee007.

Thank you for contributing!

**Comment by Ejiro-David** [comment]
I'd like to work on this.

**Comment by misspee007** [comment]
Awesome! @Ejiro-David
