### ISSUE TITLE
Increase Test Coverage 

### ISSUE THREAD

**Issue by misspee007** [chaoss/chaoss-slack-bot#34]
**Problem**: Testing is a vital part of development, and we would love to increase the test coverage of our bot.

**How to Fix It**: We’re using Jest for testing. You may want to look up the Bolt For JavaScript documentation linked in our contributing.md. This is great for contributing to hacktoberfest! Write as many quality tests as you can, and ensure to follow the contribution guide to make a quality PR. 

**What to Avoid**:
- Spamming PRs
- Duplicate tests

If you have any questions, ask @mide358 or @misspee007.

Thanks for contributing!

**Comment by nancykwantify** [comment]
Hi! May I work on this issue?

**Comment by misspee007** [comment]
Yes please @nancykwantify

**Comment by misspee007** [comment]
Hi! @nancykwantify are you still working on this?
