### ISSUE TITLE
A fix for issue #33 (Migrating documentation to wiki page)

### ISSUE THREAD

**Issue by FaithKovi** [chaoss/chaoss-slack-bot#35]
Link to the repository: https://github.com/FaithKovi/chaoss-slack-bot.git
Description: I migrated the Chaoss slack bot documentation to the wiki page. I also added a sidebar for easy navigation of the contents.

**Comment by misspee007** [comment]
Thank you so much @FaithKovi, I loved your contribution and I've merged it to the project wiki.
