### ISSUE TITLE
Create an image for the Home page of the Project Wiki page.

### ISSUE THREAD

**Issue by FaithKovi** [chaoss/chaoss-slack-bot#36]
Problem: CHAOSS Africa slack bot Wiki page which contains our documentation needs an image on the home page.

How to fix: Design an image for the Home page of the Wiki page.

Since this is a Wiki, use the steps stated in issue #33 to contribute.

**Comment by misspee007** [comment]
Hi @Ruth-ikegah, what do you think?

**Comment by Ruth-ikegah** [comment]
yeah this makes a lot of sense! @misspee007

**Comment by Sanket1308** [comment]
Hello, I will like to work on this issue. Here, we need a image for Project README, right?

**Comment by misspee007** [comment]
Hi! @Sanket1308, we need an image for the project wiki https://github.com/chaoss/chaoss-slack-bot/wiki. 
@FaithKovi are you working on this or should I assign it to Sanket?

**Comment by FaithKovi** [comment]
No I am not. Assign it to Sanket

**Comment by Sanket1308** [comment]
Thank you for assigning me!

Kindly review the design and let me know 
- if there are any changes needed.
- Is there anything else that can be written on the image?
- Do you want to change background colors?

I will make a PR once you finalise the design. 

![Chaoss](https://user-images.githubusercontent.com/79108273/194738553-250d9e0b-8a90-4b4c-abb8-112dc3267ebe.png)

**Comment by Sanket1308** [comment]
@misspee007 @Ruth-ikegah Any update?

**Comment by Sanket1308** [comment]
Yes! That will be great!

**Comment by Sanket1308** [comment]
@Anita-ihuman 

> @Sanket1308 great work with this design, I think it would be nice if we get the opinions of other community members in our slack or meetings
@Anita-ihuman 
Done, [here](https://app.slack.com/client/TV03AS82H/CV03ATA05)!

**Comment by Ruth-ikegah** [comment]
@FaithKovi please can you add this image to the wiki page?

**Comment by boradesanket13** [comment]
> @Sanket1308 great work with this design, I think it would be nice if we get the opinions of other community members in our slack or meetings

Have I have inculcated the changes suggested by community members in CHAOSS slack. Should I raise a PR? @Anita-ihuman @misspee007 @Ruth-ikegah

**Comment by Ruth-ikegah** [comment]
yes sure @boradesanket13

**Comment by FaithKovi** [comment]
> @FaithKovi please can you add this image to the wiki page?
Yes I will

**Comment by boradesanket13** [comment]
Here's the image:
![chaoss github](https://user-images.githubusercontent.com/79108273/203375172-2808b2be-ed7c-4200-825b-9e8f9f07ce8e.png)

You can make changes in design too [here](https://www.canva.com/design/DAFOhA0AAjA/sRt3dSZouhIP2TvEQmXc6A/view?utm_content=DAFOhA0AAjA&utm_campaign=designshare&utm_medium=link&utm_source=publishsharelink&mode=preview)

**Comment by Ruth-ikegah** [comment]
Thanks for your contribution @boradesanket13! You can view the wiki here: https://github.com/chaoss/chaoss-slack-bot/wiki
