### ISSUE TITLE
Mentorship Program Status Change

### ISSUE THREAD

**Issue by meetagrawal09** [chaoss/chaoss-slack-bot#42]
For the _mentorship program_ option we have hard-coded statements which need to be updated manually once the program becomes live. 
**Approach :** 
Have some **_environment variables_** that could be changed manually in order to update the status of these programs and so the reply message can be modeled accordingly

**Comment by meetagrawal09** [comment]
Below attached is the file I am pointing to
[Link to the file](https://github.com/chaoss/chaoss-slack-bot/blob/main/components/actions/mentorshipResponses.js)

**Comment by misspee007** [comment]
@meetagrawal09  that’s a great idea, assigning this to you now
