### ISSUE TITLE
[Update]: Replace CHAOSS Handbook Old Links With The New Link

### ISSUE THREAD

**Issue by misspee007** [chaoss/chaoss-slack-bot#49]
### Contact Details

preciousdanabubakar@gmail.com

### The Problem

The CHAOSS Slack Bot has the ability to send DMs, and in some of these messages, it references the CHAOSS Handbook. However, the handbook has moved to another location and we would like to update the bot with the new handbook link.

### How to Fix It

In `/components/actions/actionResponses.js`, there are 5 occurences of the handbook link. Replace all the old links with the new link.

### Additional Context

The new link: https://chaoss.community/kb-chaoss-community/

### Specific File Path(s) on the Repo to be Modified/Refered to

https://github.com/chaoss/chaoss-slack-bot/blob/main/components/actions/actionResponses.js

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sloaneee** [comment]
Hello, 
I'm just getting the hang of contributing to open source and I'll like to take on this issue.
Thanks.

**Comment by misspee007** [comment]
Awesome, it's assigned to you. Let me know if you need anything.

**Comment by sloaneee** [comment]
Hello @misspee007, Task completed, I've initiated a pull request. Please review 😊
