### ISSUE TITLE
[Enhancement]: Turn off Outreachy Prompt

### ISSUE THREAD

**Issue by misspee007** [chaoss/chaoss-slack-bot#59]
### Contact Details

preciousdanabubakar@gmail.com

### The Problem

CHAOSS is not participating in this cohort of Outreachy, so we would like to turn of the response to the `outreachy` prompt.

### How to Fix It

There's a mechanism set up to track our current outreachy participation status, in /components/actions/constants/constants.json. One way to solve this would be to observe how it is implemented in /components/actions/mentorshipResponses.js and do the same in /components/outreachyPrompt.js.

For example, 
```
const outreachyStatus = require("./actions/constants/constants.json").Outreachy.status;

async function outreachyMessage(message, say, logger) {
	try {
		if (!outreachyStatus) {
			return;
		} else {
			return await say({
				.................
			});
		}
	} catch (error) {.........}

```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by parthn2** [comment]
Hi, can I work on this?

**Comment by misspee007** [comment]
Yes you can @parthn2
