### ISSUE TITLE
[Bug]: Broken Link in Newcomer Slackbot

### ISSUE THREAD

**Issue by ElizabethN** [chaoss/chaoss-slack-bot#64]
### Contact Details

@elizabethn

### What happened?

A bug happened! There is a broken link in the newcomers slack bot that points to the [Participate](https://chaoss.community/participate) page (which no longer exists).  

### Expected behavior

We need to change the Participate page link to this one https://chaoss.community/kb-getting-started/

### Your Environment

any browser will see this

### Steps to Reproduce the Behavior

- type "newbie" in the newcomers channel, to get a message from the bot.
- click on "Help with the website". The bot will respond with some text and a link to the "Participate" page, but the link provided is not correct.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by adeyinkaoresanya** [comment]
@misspee007 I would like to be assigned to this task
