### ISSUE TITLE
[Feature]: FAQs

### ISSUE THREAD

**Issue by misspee007** [chaoss/chaoss-slack-bot#70]
### The Problem

Add an FAQ item to the newbie menu, that directs users to the FAQ section on the website.

### How to Fix It

Add an FAQ item to the newbie menu, that directs users to the FAQ section on the website.

### Specific File Path(s) on the Repo to be Modified/Refered to
- To add FAQ to the menu that pops up when a user joins the workspace, refer to the [joinTeam.js](https://github.com/chaoss/chaoss-slack-bot/blob/main/components/joinTeam.js) file. 

-  To add FAQ to the menu that pops up when a user types "newbie", refer to the [newbie.js](https://github.com/chaoss/chaoss-slack-bot/blob/main/components/newbie.js) file.  

- The [actionResponses.js](https://github.com/chaoss/chaoss-slack-bot/blob/main/components/actions/actionResponses.js) file holds the responses to be triggered when menu items are clicked. This is where you will add the link to the FAQ website.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by misspee007** [comment]
Hello @Omokiti. Yes, that should suffice. I'm waiting for feedback on the direction this feature should take, but as soon as that's settled, I will assign it to you. Thanks!

**Comment by misspee007** [comment]
@Omokiti I have edited the issue description to add more context.

**Comment by misspee007** [comment]
Hello, have you tried this? https://www.secondstate.io/articles/dco

**Comment by Omokiti** [comment]
Hi @misspee007, Thank you!! It has been fixed.
