### ISSUE TITLE
Improve developer onboarding

### ISSUE THREAD

**Issue by misspee007** [chaoss/chaoss-slack-bot#75]
### The problem:
We want to ensure that the onboarding process is as seamless as possible for anyone trying to contribute to the code for the first time. Hence, we want to make sure we cover all the basics in our contribution guide. We need someone new to go through the documentation and report any difficulties they face while setting up. This will help us to identify gaps in our documentation, so that they can be addressed.

### What to do
- Read the documentation
- Set up your development environment, following the instructions
- Report any difficulties in accessing information, understanding the docs or just getting stuff to work as expected.
- Fix the gaps identified in the documentation OR open a new issue so that someone else can fix it.

Ps: This ticket can be a collaborative effort by multiple people.

**Comment by sylon23** [comment]
I'd like to work on this too @misspee007

**Comment by misspee007** [comment]
> I'd like to work on this too @misspee007

Great! You can sync with @CatherineKiiru

**Comment by peculiaruc** [comment]
Hi @misspee007 I am interested in this issue

**Comment by CatherineKiiru** [comment]
Hi @peculiaruc have you started working on it? I wanted to first review the gaps then identify the  ares we need to work on

**Comment by peculiaruc** [comment]
> Hi @peculiaruc have you started working on it? I wanted to first review the gaps then identify the  ares we need to work on

That's great. I will wait for your feedback on that then.

**Comment by misspee007** [comment]
Wouldn’t it be nice if you all did it together on a call? (Just a suggestion)

**Comment by peculiaruc** [comment]
Great that works too

**Comment by CatherineKiiru** [comment]
@peculiaruc @misspee007  we can have a meeting next week so that we have enough time to interact with the project. When and what time will you be available?

**Comment by peculiaruc** [comment]
We can meet next week Monday at 10:30 am WAT

**Comment by CatherineKiiru** [comment]
Hi @peculiaruc Is is possible to meet on Wednesday?  I have a quite a number of meetings around that time

**Comment by peculiaruc** [comment]
Sure.Wednesday is fine. I will chat you up on Slack about your preferred time
