### ISSUE TITLE
Improve the SETUP.md documentation

### ISSUE THREAD

**Issue by CatherineKiiru** [chaoss/chaoss-slack-bot#77]
###  OAuth & Permissions Section
Include a screenshot and write up to guide a developer on how to enable the OAuth Scope for full functionality. Currently there's no guide for this particular section and it's not clear on how to go about it.

### Adding New Functions
Demonstrate how someone can add new functions. Include a screenshot and write up.

### Test the "Install App to Workspace" step
Confirm if this step under the "Tokens and Installing App" section actually leads to the Slack OAuth UI. Currently I'm an error of "slack-bot doesn’t have a bot user to install" When I click on the "Install App to Workspace" button

**Comment by CatherineKiiru** [comment]
@misspee007 Check out this issue, can you give me permission to assign issues?

**Comment by misspee007** [comment]
This looks great @CatherineKiiru. Just let me know whom you would like to assign it to, and I'll handle that for you.

**Comment by CatherineKiiru** [comment]
Thanks. @peculiaruc wanted to work on this project, you can assign this issue to her.

**Comment by misspee007** [comment]
Alright. Assigning it to you now @peculiaruc.

**Comment by peculiaruc** [comment]
Hi @misspee007
