### ISSUE TITLE
Translate Bot Token Scopes & Event Subscriptions Page

### ISSUE THREAD

**Issue by Busayo-ojo** [chaoss/chaoss-slack-bot#86]
Hello contributors, we are looking for volunteers to help us translate our Bot Token Scopes & Event Subscriptions [Page](https://github.com/chaoss/chaoss-slack-bot/wiki/Bot-Token-Scopes-&-Event-Subscriptions) into Portuguese.

Translate the wiki Bot Token Scopes & Event Subscriptions [Page](https://github.com/chaoss/chaoss-slack-bot/blob/main/Translations/Portuguese/Bot%20Token%20Scopes.md) into Portugese. 

Instructions:

Before you begin, please review our README file. It contains important information on our translation guidelines, standards, and how to get started. You can find it [here](https://github.com/chaoss/chaoss-slack-bot/blob/main/Translations/Readme.md).

If you're interested in taking on this translation task, please leave a comment on this issue. We'll assign the task to you, and you can start working on it.

Make sure to adhere to our translation guidelines provided in the [README](https://github.com/chaoss/chaoss-slack-bot/blob/main/Translations/Readme.md). This ensures consistency and quality throughout the translation.

Once the translation is complete, please create a pull request with your changes. We'll review it, and upon approval, merge it into our repository.

**Comment by Lmandavela** [comment]
Hi, would gladly help you translate the getting started page into Portuguese. @aoscode @aosccode

**Comment by antonio-pedro99** [comment]
take it @Lmandavela!

**Comment by antonio-pedro99** [comment]
Hi @Lmandavela, are you still working on this?

**Comment by Busayo-ojo** [comment]
Hi @antonio-pedro99, do you know if @Lmandavela is still working on this issue ?

**Comment by antonio-pedro99** [comment]
> Hi @antonio-pedro99, do you know if @Lmandavela is still working on this issue ?

I am not sure. Let's unsign?

**Comment by Busayo-ojo** [comment]
Sure
