### ISSUE TITLE
Translate the Contribution Guide Page

### ISSUE THREAD

**Issue by Busayo-ojo** [chaoss/chaoss-slack-bot#88]
Hello contributors, we are looking for volunteers to help us translate our Contribution Guide  [Page](https://github.com/chaoss/chaoss-slack-bot/wiki/Contribution-Guide) into Portuguese.

Translate the wiki Community Resource Page [Page](https://github.com/chaoss/chaoss-slack-bot/blob/main/Translations/Portuguese/Contribution%20Guide.md) into Portugese.

Instructions:

Before you begin, please review our README file. It contains important information on our translation guidelines, standards, and how to get started. You can find it [here](https://github.com/chaoss/chaoss-slack-bot/blob/main/Translations/Readme.md).

If you're interested in taking on this translation task, please leave a comment on this issue. We'll assign the task to you, and you can start working on it.

Make sure to adhere to our translation guidelines provided in the [README](https://github.com/chaoss/chaoss-slack-bot/blob/main/Translations/Readme.md). This ensures consistency and quality throughout the translation.

Once the translation is complete, please create a pull request with your changes. We'll review it, and upon approval, merge it into our repository.

**Comment by Stunner33** [comment]
Hey,  Can u assign this issue to me...Thanks

**Comment by Busayo-ojo** [comment]
Hi @Stunner33, Thank you for indicating interest; however, issues labeled with **AOSC** are specifically reserved for our upcoming partnership hackathon on October 15th and are not open for regular contributions. In the meantime, feel free to check our other repositories for open issues you can contribute to.

**Comment by ElisaCapololo** [comment]
Hello, I want to help translate the Contribution Guide page into Portuguese. @aosccode
