### ISSUE TITLE
Translate the Event Subscription Page

### ISSUE THREAD

**Issue by Busayo-ojo** [chaoss/chaoss-slack-bot#89]
Hello contributors, we are looking for volunteers to help us translate our Event Subscription [Page](https://github.com/chaoss/chaoss-slack-bot/wiki/Bot-Token-Scopes-&-Event-Subscriptions) into Portuguese.

Translate the wiki Event Subdcription [Page](https://github.com/chaoss/chaoss-slack-bot/blob/main/Translations/Portuguese/Event%20Subscriptions.md) into Portugese.

Instructions:

Before you begin, please review our README file. It contains important information on our translation guidelines, standards, and how to get started. You can find it [here](https://github.com/chaoss/chaoss-slack-bot/blob/main/Translations/Readme.md).

If you're interested in taking on this translation task, please leave a comment on this issue. We'll assign the task to you, and you can start working on it.

Make sure to adhere to our translation guidelines provided in the [README](https://github.com/chaoss/chaoss-slack-bot/blob/main/Translations/Readme.md). This ensures consistency and quality throughout the translation.

Once the translation is complete, please create a pull request with your changes. We'll review it, and upon approval, merge it into our repository.

**Comment by Francisco-dos-Santos** [comment]
Estou disponível para traduzir a pagina em português @aosccode

**Comment by aosccode** [comment]
@Francisco-dos-Santos podes começar mano! E submeter pelo menos 30% da tradução.

**Comment by Francisco-dos-Santos** [comment]
@aosccode está bem
