### ISSUE TITLE
Translate the Getting Started With Bolt For Javascript Page

### ISSUE THREAD

**Issue by Busayo-ojo** [chaoss/chaoss-slack-bot#90]
Hello contributors, we are looking for volunteers to help us translate the Getting Started With Bolt For Javascript [Page](https://github.com/chaoss/chaoss-slack-bot/wiki/Getting-Started-With-Bolt-for-JavaScript) into Portuguese.

Translate the wiki Getting Started With Bolt For Javascript [Page](https://github.com/chaoss/chaoss-slack-bot/blob/main/Translations/Portuguese/Getting%20Started%20With%20Bolt%20For%20Javascript.md) into Portugese.

Instructions:

Before you begin, please review our README file. It contains important information on our translation guidelines, standards, and how to get started. You can find it [here](https://github.com/chaoss/chaoss-slack-bot/blob/main/Translations/Readme.md).

If you're interested in taking on this translation task, please leave a comment on this issue. We'll assign the task to you, and you can start working on it.

Make sure to adhere to our translation guidelines provided in the [README](https://github.com/chaoss/chaoss-slack-bot/blob/main/Translations/Readme.md). This ensures consistency and quality throughout the translation.

Once the translation is complete, please create a pull request with your changes. We'll review it, and upon approval, merge it into our repository.

**Comment by ElisaCapololo** [comment]
Hello, I want to help translate the Getting Started With Bolt For Javascript page into Portuguese.

**Comment by Lmandavela** [comment]
Hi, Elisa would gladly help you translate it to Portuguese.

**Comment by antonio-pedro99** [comment]
@aosccode

**Comment by aosccode** [comment]
@ElisaCapololo take it and submit a draft PR

**Comment by aosccode** [comment]
@Lmandavela please take a look at https://github.com/chaoss/chaoss-slack-bot/issues?q=is%3Aissue+is%3Aopen+label%3AAOSC to see more issues you can work on
