### ISSUE TITLE
[Docs]: Contributing to the wiki (a guide)

### ISSUE THREAD

**Issue by misspee007** [chaoss/chaoss-slack-bot#98]
### Contact Details

preciousdanabubakar@gmail.com or Precious Abubakar on Slack

### The Problem

The process of contributing to a GitHub wiki is slightly different from the regular workflow. We would like to capture this in the [contributing guide](https://github.com/chaoss/chaoss-slack-bot/blob/main/CONTRIBUTING.md).

### How to Fix It

Add a section in the [Contributing.MD](https://github.com/chaoss/chaoss-slack-bot/blob/main/CONTRIBUTING.md). The heading can be "Contributing to the wiki" or anything more descriptive you can come up with. Include images where possible.

Resources:
Refer to GitHub's documentation on [Adding or editing wiki pages locally](https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages#adding-or-editing-wiki-pages-locally).

Ps: We will add additional steps, but I'm working on that and will communicate them to you. Let's start here.

Thanks! 😊

### Specific File Path(s) on the Repo to be Modified/Refered to

https://github.com/chaoss/chaoss-slack-bot/blob/main/CONTRIBUTING.md

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by misspee007** [comment]
> Hello, I would like to help by contributing to this.

Hi, I’ll assign it to you. Thank you!

**Comment by ise8933** [comment]
Hello I was wondering if I could still contribute to this?

**Comment by misspee007** [comment]
> Hello I was wondering if I could still contribute to this?

Hey, I'll get back to you on this

**Comment by misspee007** [comment]
Hi @ElisaCapololo. Are you still working on this, or would you like @ise8933 to take it up?

**Comment by ElisaCapololo** [comment]
Yes, I still working on this. @misspee007

**Comment by misspee007** [comment]
> Yes, I'm still working on it. @misspee007 . But if there's anything @ise8933 can help with, that's fine with me.

Alright then. You've been on it for quite some time, though. Have you encountered any blockers? Let me know if there's anything you need

**Comment by ElisaCapololo** [comment]
Hello @misspee007 . I'd like to know what the next steps are, since the first steps to contribute have already been taken and the merge has been accepted.

**Comment by misspee007** [comment]
> Hello @misspee007 . I'd like to know what the next steps are, since the first steps to contribute have already been taken and the merge has been accepted.

Hi @ElisaCapololo. 
After reviewed the "Contributing to the wiki" guide again, I've realised that all we really need there is the [Adding or editing wiki pages locally](https://github.com/chaoss/chaoss-slack-bot/blob/main/CONTRIBUTING.md#adding-or-editing-wiki-pages-locally) section. I've extracted the bullet points so that you won't have to do too much work. Kindly update it. Feel free to make edits/propose changes. 

Also, please try following the steps. I would like to see if this works for someone without admin priviledges. 

Thanks!

## Contributing to the wiki
- Clone the wiki repository 
`$ git clone https://github.com/chaoss/chaoss-slack-bot.wiki.git `

- Navigate to the wiki folder
`$ cd chaoss-slack-bot.wiki`

- Create a new branch 
`$ git checkout -b wiki/feature-name`

- You can add new files or edit existing ones and commit your changes.
`
$ git add .
$ git commit -s -m "descriptive commit message"
$ git push -u origin wiki/feature-name
`

- When you're done, add a comment on the issue you're addressing and tag a reviewer. The comment should include a link to the branch that holds your changes. At this point, all you need to do is wait for feedback!

**Comment by misspee007** [comment]
> Hello I was wondering if I could still contribute to this?

Hi @ise8933, there's another open documentation issue [here](https://github.com/chaoss/chaoss-slack-bot/issues/101), you can check it out.

**Comment by misspee007** [comment]
Hey @ElisaCapololo. If you're having trouble with this, let me know if you need anything or if you want me to take it up.

**Comment by ElisaCapololo** [comment]
> > Hi @misspee007, I was about to message you today, yes I'm having a little issue and need some help. I've already made the requested changes, but it seems like the DCO is missing, but then I pushed with the DCO but it's still the same.
> 
> I see. It could be because you have old commits that weren't properly signed off, and you're trying to fix it by signing off new commits. You need to rebase the branch. Please follow the instructions [here](https://github.com/chaoss/chaoss-slack-bot/blob/main/CONTRIBUTING.md#how-to-fix-a-failed-dco-check)

Thank you so much. It is working

**Comment by ise8933** [comment]
@misspee007 @ElisaCapololo Hi! I was looking through the docs and thought that a section for user scopes may be helpful! I was trying to commit to the wiki to contribute but for some reason i am being denied access. So I am attaching a screenshot of the table I made along with the source code
[UserScopes.md](https://github.com/chaoss/chaoss-slack-bot/files/15203895/UserScopes.md)
. 

![image](https://github.com/chaoss/chaoss-slack-bot/assets/90360951/1be76cdb-03a9-4f13-bb04-d30d67e5ed50)

**Comment by misspee007** [comment]
> @misspee007 @ElisaCapololo Hi! I was looking through the docs and thought that a section for user scopes may be helpful! I was trying to commit to the wiki to contribute but for some reason i am being denied access. So I am attaching a screenshot of the table I made along with the source code [UserScopes.md](https://github.com/chaoss/chaoss-slack-bot/files/15203895/UserScopes.md) .
> 
> ![image](https://private-user-images.githubusercontent.com/90360951/327852963-1be76cdb-03a9-4f13-bb04-d30d67e5ed50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5MjQ4MzgsIm5iZiI6MTcxNDkyNDUzOCwicGF0aCI6Ii85MDM2MDk1MS8zMjc4NTI5NjMtMWJlNzZjZGItMDNhOS00ZjEzLWJiMDQtZDMwZDY3ZTVlZDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA1VDE1NTUzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzNDc3MDMxZjQ0YTJlYWM0MTBmYzMyYzgyMTc5OGFjYjUwMTlhOTBhMTRkYWJmZmRkOTZhNmYzOWY4Y2QxNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZYh7EebI5zDerFRx7I-NMHD5Ao1Wji-rtNGWB_2u480)

@ise8933 Unfortunately, only admins can commit directly to a GitHub wiki, but we're still working on alternatives. Thanks for this, I'll look into it!

**Comment by misspee007** [comment]
@ElisaCapololo I noticed that you have 3 pull requests open. If they're similar, please close the redundant ones, and [request a review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) on the relevant one(s).

**Comment by ElisaCapololo** [comment]
@misspee007 I've already closed the other two open PRs, but I can't do the review, I'm following the link you sent, but where the review appears, there's no one to ask to review the code.
